Hw02 express
ludmila-usyk/nodejs-homework-template-rest-api pull request #1
Opened 2021-12-29 13:37 UTC by ludmila-usyk

2022-01-04 21:10 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
почему данная функция асинхронная?

2022-01-04 21:10 UTC, KirillKulakow commented on model/index.js
> +const getContactById = async (contactId) => {
тот же вопрос

2022-01-04 21:11 UTC, KirillKulakow commented on model/index.js
> +  const [contact] = contacts.filter((contact) => contact.id === contactId)
было бы правильней и более оптимальней использовать find а не filter

2022-01-04 21:14 UTC, KirillKulakow commented on model/index.js
> +import randomUUID from 'crypto'
данная функция так не работает
`import { randomUUID } from "crypto"` - так будет работать

2022-01-04 21:14 UTC, KirillKulakow commented on model/index.js
> +import randomUUID from 'crypto'
https://nodejs.org/api/crypto.html#cryptorandomuuidoptions

2022-01-04 21:16 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body }
какой смысл перезаписывать ид контакта?
если `contacts[index]` тебе вернет все поля контакта (в том числе и ид)

2022-01-04 21:17 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body }
+ это все можно записать в одну строку

2022-01-04 21:18 UTC, KirillKulakow requested changes
Need fix

2022-01-05 08:08 UTC, ludmila-usyk commented on model/index.js
> +const getContactById = async (contactId) => {
а почему бы и нет?

2022-01-05 08:08 UTC, ludmila-usyk commented on model/index.js
> +const listContacts = async () => {
а почему бы и нет?

2022-01-05 08:10 UTC, ludmila-usyk commented on model/index.js
> +  const [contact] = contacts.filter((contact) => contact.id === contactId)
ок

2022-01-05 12:56 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
https://learn.javascript.ru/async-await
Общепринято - что если ты используешь async метод - он должен возвращать промис (Promise)
если функция ничего не возвращает, тогда внутри должен быть await другого промиса как минимум

2022-01-05 12:56 UTC, KirillKulakow commented on model/index.js
> +const getContactById = async (contactId) => {
оставил коммент в прошлом

2022-01-05 19:39 UTC, KirillKulakow commented on .vscode/launch.json
> +{
удалить файл и добавить в gitignore

2022-01-05 19:41 UTC, KirillKulakow commented on model/index.js
> +const contacts = await listContacts();
у тебя же есть переменная contacts из импорта, зачем создавать эту константу? у тебя прям какой то infinite loop (бесконечный цикл) получается

2022-01-05 19:42 UTC, KirillKulakow requested changes
Need fix

2022-01-05 20:19 UTC, ludmila-usyk commented on model/index.js
> +const contacts = await listContacts();
тогда, получается, мне єтоне нужно? import contacts from './contacts.json'

2022-01-06 20:27 UTC, KirillKulakow commented on .gitignore
> +
вместо этого всего просто напиши строку `.vscode`

2022-01-06 20:28 UTC, KirillKulakow approved these changes

2022-01-07 21:19 UTC, merged